### ISSUE TITLE
File Extension Name

### ISSUE THREAD

**Issue by JBYT27** [JBYT27/PyScript-Compiler#1]
Hello, so I've been thinking about the file extension, and I *just* found out that there already is a language with a `.ps` file extension (lmao). So for now, I've switched it to `.pys`, but do you guys have any other suggestions? 

Thanks!
- JB

**Comment by darkdarcool** [comment]
maybe `index.pysc`

**Comment by darkdarcool** [comment]
also maybe you should make the lang in js? It just seems better as you'll get better stuff and alerts. But you can do python(idk why you have bhtml stuff tho)

**Comment by JBYT27** [comment]
oooh, thanks! and okie, ill think about transfering later on, or i might stick to python. Yeah, i was using that for reference for later code ;)

**Comment by darkdarcool** [comment]
ok
